### ISSUE TITLE
wrap bug  

### ISSUE THREAD

**Issue by jasorgho** [outsideris/atom-angularjs#4]
Hi 
after choosing necessary directive and pressing ENTER key my editor does wrong wrap  

![2015-05-15_1730](https://cloud.githubusercontent.com/assets/980474/7654779/361db3da-fb28-11e4-8023-2828214caa7f.png)
and video: http://screencast.com/t/FA9mVMf8

**Comment by outsideris** [comment]
Thank you for reporting.
But this project was merged into <https://github.com/angular-ui/AngularJS-Atom>. So it isn't maintain no longer.
Please use AngularJS-Atom and report on the repository if you have still the problem.
